### ISSUE TITLE
Store duress password in unix crypt format

### ISSUE THREAD

**Issue by rechner** [nuvious/pam-duress#14]
https://github.com/nuvious/pam-duress/blob/30d7065e173d6062384387af10e74e8c1c138d48/src/duress.c#L193

Using the [modular crypt(3) format](https://www.man7.org/linux/man-pages/man3/crypt.3.html) from glibc instead of specifying a hash, will make this a bit more future-proof, storing passwords the same way as standard password authentication.

**Comment by Artoria2e5** [comment]
> From what I can see crypt() has mixed support for algorithms across BSD and Mac

Yeah. I think the argument for using MCF would be the ability to switch to other hash algos without breaking the format. The actual implementation will be likely independent of the `libc` with things like [libxcrypt](https://github.com/besser82/libxcrypt) being used on some platforms.

**Comment by nuvious** [comment]
> > From what I can see crypt() has mixed support for algorithms across BSD and Mac
> 
> Yeah. I think the argument for using MCF would be the ability to switch to other hash algos without breaking the format. The actual implementation will be likely independent of the `libc` with things like [libxcrypt](https://github.com/besser82/libxcrypt) being used on some platforms.

That sounds like the right path then. Definitely would like to leverage a common standard and this looks more appropriate than openssl and proprietary storage mechanisms at least at first glance.

**Comment by nuvious** [comment]
I reviewed this a bit more and decided to close it without modifying the current convention. Per @Artoria2e5, with the script being consumed as the salt the hash both acts as a means to verify the password and ensure the integrity of the script in one step. I may explore libxcrypt in the future but would be a bit of an overhaul I don't have bandwidth for at the moment (but will make time to review anyone willing to offer an implementation as a PR). Right now the implementation satisfies the needs for the secure hash as well as script integrity protection to satisfy #20.
