### ISSUE TITLE
How can I get it working on gentoo?

### ISSUE THREAD

**Issue by max12mx13** [nuvious/pam-duress#32]
Hello, first of all can I just say thank you for this project as it has worked well on other systems. However, on my gentoo install I am running into a few problems.
Firstly, the system-auth vs common-auth issue, I followed the guidance for arch users however I do not know if it has worked for reasons I will state later
Next, the library was placed in `/lib/security` and was not being detected. I moved it to `/lib64/security` and `su` stopped spitting out an error saying it could not find the library
However, it still did not work. I attempted to log the PAM while ssh'ing in with and without my duress password. The only difference between the two was this line:
`pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=::1  user=max`
This suggests pam_duress.so is not even being loaded so that's why I believe that the system-auth might not be valid
I am not knowledgeable at all with PAM so im sure there is an easy answer that I am just missing.
Any help is appreciated! Max

**Comment by nuvious** [comment]
Closing this issue as it's out of scope for the project. Trying to focus more on bugs related to the module code itself and less about different OS flavor PAM configurations. Still welcome pull requests to create walkthroughs of how to install on various flavors of Linux but only really have the bandwidth to test in Arch and Debian variants at the moment and will only be maintaining installation guides for Debian variants.
