### ISSUE TITLE
I would like to translate this for macOS

### ISSUE THREAD

**Issue by federico22285** [nuvious/pam-duress#40]
Hey :-) 

Does anyone, especially the author have tried or has some opinion if this will work for macOS?, I have to study the differences when it comes to how PAM operates in each of this systems tho. 

Thanks!

**Comment by nuvious** [comment]
We had a pull request in the past that added Mac OS compatibility and I've started documentation on distro-specific implementations. I don't have a Mac myself but if you're interested in figuring out how to implement this on a Mac with its PAM configuration, you're welcome to fork and contribute updates to the documentation.

Sorry the project hasn't been as active, new job has me very busy lately and haven't had much time to go back to this project.
