### ISSUE TITLE
KDE plasma lockscreen (kscreenlocker) support

### ISSUE THREAD

**Issue by white-chestnut** [nuvious/pam-duress#45]
Please give support on how to set up pam-duress for KDE lockscreen (kscreenlocker).
I successfully set up pam-duress as described and it is working as expected for login but not on the lockscreen of KDE plasma.

Please be so kind and support to get this running on lockscreen for KDE plasma as well.

Thank you in advance

System: Debian 12.2 / Plasma 5.27.5
No /etc/pam.d/kde config available

**Comment by nuvious** [comment]
@white-chestnut , not sure if you're still interested in this issue, but this module is geared towards pam support and OS specific or authentication method specific support isn't necessarily provided. I will accept PR's for folks providing tutorials for specific distros, desktop environments, etc. However, the foundational repo support I will be providing will be strictly for its support of PAM and not different distribution's use of PAM.
