### ISSUE TITLE
scripts not executed on debian bookworm

### ISSUE THREAD

**Issue by m6n50u7** [nuvious/pam-duress#47]
as far as I checked, I did all of the required steps.
but when I'm in test phase the duress password does give successful login but doesn't trigger the related hello world script.

**Comment by nuvious** [comment]
@m6n50u7, spinning up a VM now. In the meantime can you check /var/log/syslog or /var/log/auth for any entries that might show a specific error?

**Comment by nuvious** [comment]
@m6n50u7 P.S. may need to rebuild the module with debug settings to see any output.

**Comment by nuvious** [comment]
Gotcha, that is intentional to keep the module from producing unnecessary output. For testing you may want to redirect script command outputs to logs, maybe set a variable to a log path for testing and /dev/null once you have it setup to your liking.

**Comment by m6n50u7** [comment]
yeah, that what I did to check if the output is muted.
you should update the test phase tutorial.

**Comment by nuvious** [comment]
I'll double check it to make sure it is working as expected. If you want contribution credit, feel free to fork, adjust and open a pull request. I'll double check it tomorrow otherwise I'm the VM I spun up and check it out myself and update the docs.

**Comment by nuvious** [comment]
Found the issue was related to the kind of build that the test was being run with. Debug build would produce the hello world output and a standard build would not. Adjusted proposed PR #48 to prevent a user from having to have a specific build type to run the demo.
