### ISSUE TITLE
[FR] macOS support?

### ISSUE THREAD

**Issue by NightMachinary** [nuvious/pam-duress#5]

**Comment by cormacrelf** [comment]
Yeah, it needed a few tweaks but can be done pretty easily.

![image](https://user-images.githubusercontent.com/378760/130413518-8e7154d1-3dc5-4520-99fa-6009b2e78f5b.png)

**Comment by cormacrelf** [comment]
The SIGSEGV shouldn't be happening when you hit ctrl-c so that's a bug

**Comment by aniqueta** [comment]
Has this been tested and/or would it make sense to also use this with /etc/pam.d/authorization (macOS logon) and with /etc/pam.d/screensaver (macOS lock screen)? Thanks.

**Comment by cormacrelf** [comment]
I mean at the age of this project, don't seriously use it. It has been "tested" but it hasn't been tested tested. But PAM works the same for all of these things, it would probably work. Give it a go (read my advice in #6 before you do though) and let us know what works.
